name: CICD
on:
  push:
    branches: [dev, releases]
  pull_request_target:
    types:
      - closed
    branches:
      - main
env:
  DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
  DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN }}
  REPO_DIRECTORY: ${{ vars.REPO_DIRECTORY }}
  CLUSTER_ID: ${{ vars.CLUSTER_ID }}

permissions:
  checks: write
  pull-requests: write
jobs:
  OnPush:
    if: github.ref_name == 'dev'
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      
    #- name: Generate and save AAD Token
    #  run: |
    #    echo "DATABRICKS_TOKEN=$(curl -X POST -H 'Content-Type: application/x-www-form-urlencoded' \
    #      https://login.microsoftonline.com/9f37a392-f0ae-4280-9796-f1864a10effc/oauth2/v2.0/token \
    #      -d 'client_id=d1c98985-cb56-4b14-ba47-f06ad92ce69a' \
    #      -d 'grant_type=client_credentials' \
    #      -d 'scope=2ff814a6-3304-4ab8-85cb-cd0e6f879c1d%2F.default' \
    #      -d 'client_secret=${{ secrets.AZURE_CREDENTIALS }}' |  jq -r  '.access_token')" >> $GITHUB_ENV
          
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      
    - name: Install libraries
      run: |
        pip install --upgrade pip nutter
    - name: install-databricks-cli
      uses: microsoft/install-databricks-cli@v1.0.0

    - name: Update databricks repo
      run: |
        databricks repos update --path $REPO_DIRECTORY --branch "${{github.ref_name}}"
        
    - name: Run Tests
      run: |
        nutter run "$REPO_DIRECTORY/unit-tests/" --cluster_id $CLUSTER_ID --recursive --junit_report --timeout 500
    
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |                  # Name of the check run which will be created
          '**/test-*.xml'     
        
   
  OnRelease:
    if: startsWith(github.ref_name, 'main')
    environment: prod
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install libraries
      run: |
        pip install --upgrade pip nutter
    - name: install-databricks-cli
      uses: microsoft/install-databricks-cli@v1.0.0

    - name: Update databricks repo
      run: |
        databricks repos update --path $REPO_DIRECTORY --branch "${{github.ref_name}}"

    - name: Run Tests
      run: |
        nutter run "$REPO_DIRECTORY/unit-tests/" --cluster_id $CLUSTER_ID --recursive --junit_report --timeout 500

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          '**/test-*.xml'
