name: CICD
on:
  push:
    branches: [dev,release ]
    
env:
  DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
  DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN }}
  DEV_DIRECTORY: /Repos/pratik.kewalramani@databricks.com/github-actions-demo/
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      
    - name: Install libraries
      run: |
        pip install --upgrade pip nutter
    - name: install-databricks-cli
      uses: microsoft/install-databricks-cli@v1.0.0

    - name: Update databricks repo
      run: |
        databricks repos update --path $DEV_DIRECTORY --branch "${{GITHUB_REF_NAME}}"