name: CICD
on:
  push:
    branches: [dev, releases]
  pull_request_target:
    types:
      - closed
    branches:
      - main
env:
  DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
  DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN }}
  DEV_DIRECTORY: /Repos/pratik.kewalramani@databricks.com/github-actions-demo
  CLUSTER_ID: 0214-013545-noz35upv
  
jobs:
  OnPush:
    if: github.ref_name == 'dev'
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      
    - name: Install libraries
      run: |
        pip install --upgrade pip nutter
    - name: install-databricks-cli
      uses: microsoft/install-databricks-cli@v1.0.0

    - name: Update databricks repo
      run: |
        databricks repos update --path $DEV_DIRECTORY --branch "${{github.ref_name}}"
        
    - name: Run a databricks notebook
      uses: databricks/run-notebook@v0
      with:
       local-notebook-path: unit-tests/test_with_percent_run
       git-commit: ${{ github.event.pull_request.head.sha }}
       new-cluster-json: >
         {
           "num_workers": 1,
           "spark_version": "10.4.x-scala2.12",
           "node_type_id": "Standard_D3_v2"
          }    
    - name: Run Tests
      run: |
        nutter run "$DEV_DIRECTORY/unit-tests/" --cluster_id $CLUSTER_ID --recursive --junit_report --timeout 500
 
   
  OnRelease:
    if: startsWith(github.ref_name, 'main')
    environment: prod
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install libraries
      run: |
        pip install --upgrade pip nutter
    - name: install-databricks-cli
      uses: microsoft/install-databricks-cli@v1.0.0

    - name: Update databricks repo
      run: |
        databricks repos update --path $DEV_DIRECTORY --branch "${{github.ref_name}}"

    - name: Run Tests
      run: |
        nutter run "$DEV_DIRECTORY/unit-tests/" --cluster_id $CLUSTER_ID --recursive --junit_report --timeout 500

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          **/test-*.xml
