name: CICD
on:
  push:
    branches: [dev, releases]
  pull_request_target:
    types:
      - closed
    branches:
      - main
env:
  DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
  DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN }}
  REPO_DIRECTORY: ${{ vars.REPO_DIRECTORY }}
  CLUSTER_ID: ${{ vars.CLUSTER_ID }}
  
jobs:
  OnPush:
    if: github.ref_name == 'dev'
    environment: dev
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      
    - name: Install libraries
      run: |
        pip install --upgrade pip nutter
    - name: install-databricks-cli
      uses: microsoft/install-databricks-cli@v1.0.0

    - name: Update databricks repo
      run: |
        databricks repos update --path $REPO_DIRECTORY --branch "${{github.ref_name}}"
        
    - name: Run Tests
      run: |
        nutter run "$REPO_DIRECTORY/unit-tests/" --cluster_id $CLUSTER_ID --recursive --junit_report --timeout 500
    
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |                  # Name of the check run which will be created
          '**/test-*.xml'     
        
   
  OnRelease:
    if: startsWith(github.ref_name, 'main')
    environment: prod
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install libraries
      run: |
        pip install --upgrade pip nutter
    - name: install-databricks-cli
      uses: microsoft/install-databricks-cli@v1.0.0

    - name: Update databricks repo
      run: |
        databricks repos update --path $REPO_DIRECTORY --branch "${{github.ref_name}}"

    - name: Run Tests
      run: |
        nutter run "$REPO_DIRECTORY/unit-tests/" --cluster_id $CLUSTER_ID --recursive --junit_report --timeout 500

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          **/test-*.xml
